### ISSUE TITLE
Error in api_scrape

### ISSUE THREAD

**Issue by kevinoden** [stephematician/statsnbaR#2]
tried your first example, yet get the following error:

 > dleague_players <- get_players(league='d-league')
No encoding supplied: defaulting to UTF-8.
Error in api_scrape("player_registry", filters = filters) : 
  [stats_nba scrape] invalid result returned by stats.nba.com endpoint

using the following:
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] statsnbaR_0.1   httr_1.3.1      devtools_1.12.0 dplyr_0.5.0    

loaded via a namespace (and not attached):
 [1] magrittr_1.5     assertthat_0.2.0 R6_2.2.2         DBI_0.7          tools_3.2.2      withr_2.1.0      tibble_1.3.0     curl_2.5        
 [9] Rcpp_0.12.10     memoise_1.1.0    xml2_1.1.1       git2r_0.18.0     digest_0.6.8

**Comment by stephematician** [comment]
Hi Kevin, I'm not sure what your particular issue is. What is the result of:

    GET(url="http://google.com")

**Comment by stephematician** [comment]
I have made a small set of changes to the query that is passed on to stats.nba.com; let me know if this changes anything.

As of the current commit (0d92d87) I am able to call `get_players(league='d-league')` and get a sensible result.

Aside: Maybe I need to switch `d-league` to `g-league`, too.

**Comment by kevinoden** [comment]
Get seems to work

Response [http://www.google.com/]
  Date: 2018-01-02 16:18
  Status: 200
  Content-Type: text/html; charset=ISO-8859-1
  Size: 11 kB
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta content="Search the world's information, includin...
</style><style>body,td,a,p,.h{font-family:arial,sans-serif}body{margin:0;overflow-y:scroll}#gog{padding:3px 8px 0}td{line-height:.8em}.gac_m t...
if (!iesg){document.f&&document.f.q.focus();document.gbqf&&document.gbqf.q.focus();}
}
})();</script><div id="mngb"> <div id=gbar><nobr><b class=gb1>Search</b> <a class=gb1 href="http://www.google.com/imghp?hl=en&tab=wi">Images</...
>

**Comment by kevinoden** [comment]
Seems to have been a corrupt file problem on my side.  I reinstalled and its working fine now.

Thanks for the prompt response.
